# Generated by Django 4.2.27 on 2026-09-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alerts", "0033_migrate_legacy_match_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="node_id",
            field=models.CharField(blank=True, help_text="节点ID快照", max_length=100, null=True),
        ),
    ]
