[program:opspilot_celery]
command=celery -A apps.core.celery worker --loglevel=info --pool prefork --concurrency=%(ENV_OPSPILOT_CELERY_CONCURRENCY)s --max-tasks-per-child=%(ENV_CELERY_MAX_TASKS_PER_CHILD)s --max-memory-per-child=%(ENV_CELERY_MAX_MEMORY_PER_CHILD)s -Q opspilot_channel,opspilot_wiki,opspilot_maintenance -n opspilot@%%h
directory=/apps
autostart=true
priority=10
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
