[program:patch_maintenance]
command=celery -A apps.core.celery worker --loglevel=info --pool prefork --concurrency=1 --max-tasks-per-child=%(ENV_CELERY_MAX_TASKS_PER_CHILD)s --max-memory-per-child=%(ENV_CELERY_MAX_MEMORY_PER_CHILD)s -Q patch_maintenance -n patch-maintenance@%%h
directory=/apps
autostart=true
priority=10
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
